# Generated by Django 5.2.15 on 2026-07-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(blank=True, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
